print(hello, world)
print(hello, pull)
print(hello, fetch)
print(hello, pull)
print(hello, rebase)
print(hello, rebase)
print(hello, rebase)
print(hello, merge)
print(hello, cherry)
print(hello, I'm correct cherry)
